### ISSUE TITLE
multi-line equations not generating MathML

### ISSUE THREAD

**Issue by javierfer** [Sukii/Metaforml#1]
When the equations are in one line, the MathML output is generated successfully. When the equations contain at least 2 lines, no MathML is generated.

Example:
![eq-issue](https://cloud.githubusercontent.com/assets/11413795/8263563/694c766a-16b2-11e5-9ee9-d3ca158e9230.png)

**Comment by javierfer** [comment]
I found that the issue is in the XmlGeneratorVisitor class, in the method:

```
public void visit(PILE aPile) {
        Element el = new Element("pile");
        current.peek().appendChild(el);
}
```

Piles are used when the equations contain multiple lines. In this case, the Pile object is correct, but it is not processed successfully in the visitor.

I will create a pull request with the fix.

Regards,
Javier

**Comment by javierfer** [comment]
Hi, I want to push my branch with the fix, to create the pull request, but I can't:

```
ERROR: Permission to Sukii/Metaforml.git denied to javierfer.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Sukii** [comment]
I will fix that today.

**Comment by Sukii** [comment]
Oops! my mistake, I added someone else instead of your name as collaborator.

**Comment by javierfer** [comment]
Done. I created the pull request with the PILE fixes.

Regards,
Javier
