### ISSUE TITLE
Mathtype to MathML Ruby gem

### ISSUE THREAD

**Issue by jure** [Sukii/Metaforml#7]
Hey folks, I opened this as an issue since I don't have any other way of contacting you. I just wanted to let you know that I've created a [`mathtype`](https://github.com/jure/mathtype) and a [`mathtype_to_mathml`](https://github.com/Tahi-project/mathtype_to_mathml) Ruby gem, which are almost feature complete. Here are my sample/test MathType binaries converted using this gem: 
http://cl.ly/2R0N3E161i1b

I hope that you'll find it useful in your own efforts!

**Comment by SMahalakshmi** [comment]
Awesome! I will look into this and share my findings. Thanks

**Comment by jure** [comment]
Thanks! The `mathtype` gem converts from the binary MTEF to an XML MTEF form. `mathtype_to_mathml` then uses XSLTs with a bit of custom Ruby for character ranges and subscript/superscript support to convert to MathML.

**Comment by SMahalakshmi** [comment]
Hi Jure
We have tested the latest release of MathML Torture Test suite" offered by Mozilla (https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/MathML_Torture_Test). It works fine. Out of 28 equations, 23 equations come out well. 
Please find the attached zip file which contains the problematic bin files and test result. Could you please check this equations?
Note: Not able to attach the zip file, so I have renamed to jpg. Please change to zip 
![bin](https://cloud.githubusercontent.com/assets/8802420/9754328/94819cf2-56e5-11e5-90d6-9b966e8f4789.jpg)

**Comment by jure** [comment]
Thank you very much @SMahalakshmi, I'll take a look!
